### ISSUE TITLE
Erroneous Metadata Failure

### ISSUE THREAD

**Issue by UmpquaRiver** [mrsobakin/lrc-dl#2]
I've tried running a number of audio files through which I know to have typical ID3 metadata tags using `lrc-dl <path-to-file> -c config.toml` , yet the software tells me: `Song is missing title or artist name`

It hasn't bitten anything I've thrown at it yet... so if I'm the erroneous one, I haven't figured out why yet. 

Installed via readme instructions on Fedora 40

**Comment by mrsobakin** [comment]
Hi, could you please share your audio files or their `ffprobe` output? I can't reproduce the issue on any files I have.

**Comment by UmpquaRiver** [comment]
Random example song: [song.zip](https://github.com/user-attachments/files/18243369/song.zip)

ffprobe (ffprobe "01 - Rocky Mountain High - Live 1995.mp3"):
> ffprobe version 6.1.2 Copyright (c) 2007-2024 the FFmpeg developers
>   built with gcc 14 (GCC)
>   configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-lcms2 --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcodec2 --enable-libcdio --enable-libdrm --enable-libjack --enable-libjxl --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libharfbuzz --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-libplacebo --enable-librsvg --enable-librav1e --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libshaderc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libvpl --enable-runtime-cpudetect
>   libavutil      58. 29.100 / 58. 29.100
>   libavcodec     60. 31.102 / 60. 31.102
>   libavformat    60. 16.100 / 60. 16.100
>   libavdevice    60.  3.100 / 60.  3.100
>   libavfilter     9. 12.100 /  9. 12.100
>   libswscale      7.  5.100 /  7.  5.100
>   libswresample   4. 12.100 /  4. 12.100
>   libpostproc    57.  3.100 / 57.  3.100
> Input #0, mp3, from '01 - Rocky Mountain High - Live 1995.mp3':
>   Metadata:
>     title           : Rocky Mountain High - Live 1995
>     artist          : John Denver
>     album_artist    : John Denver
>     album           : The Wildlife Concert
>     disc            : 01
>     track           : 01
>     TORY            : 1995
>     date            : 1995-06-13
>   Duration: 00:04:22.66, start: 0.023021, bitrate: 261 kb/s
>   Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 256 kb/s
>     Metadata:
>       encoder         : Lavc58.54
>   Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 640x640 [SAR 118:118 DAR 1:1], 90k tbr, 90k tbn (attached pic)
>     Metadata:
>       title           : Cover
>       comment         : Cover (front)

And when I run `lrc-dl "/home/jayj/01 - Rocky Mountain High - Live 1995.mp3"`, the result is `[lrc-dl] /home/jayj/01 - Rocky Mountain High - Live 1995.mp3: Song is missing title or artist name`. MPV and other players are also able to pick up the metadata.

**Comment by mrsobakin** [comment]
Seems like lrc_dl just wasn't able to parse ID3v2 metadata from mp3 files, and I only tested it on FLACs. I've uploaded a fix. Try running it now.

**Comment by UmpquaRiver** [comment]
I've rebuilt and tried running lrc-dl on several different formats and they all seem to go through great now. I hadn't thought of running FLAC through even though I have quite a bit of that... oops!

Thanks for the fix.
